import Head from "next/head";

import ChatGptForm from "../components/ChatGptForm";





export default function Home() {

  
  return ( 
    <>
     <Head>
          <title>Camerota</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ChatGptForm /> 
    
    </>
 
  
  );
}
